name: CI

# Controls when the workflow will run
on:
  release:
    types: [published]
  workflow_dispatch:

env:
  registry_name: ghcr.io
  image_name: ${{ github.repository_owner }}/azure-iotedge-plc-publisher
  module_path: ./src/PlcPublisher/modules/PLC-Publisher/

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:
      # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:  
          - name: amd64
            platformName: linux/amd64
          - name: arm64v8
            platformName: linux/arm64/v8

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with: 
          submodules: true     

      - id: docker-tag
        uses: yuya-takeyama/docker-tag-from-github-ref-action@v1
      
      - name: Docker Login
        # You may pin to the exact commit or the version.
        uses: docker/login-action@v2.0.0
        with:
          registry: ${{ env.registry_name }}
          username:  ${{ github.actor }}
          password:  ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push ${{ matrix.arch.name }}
        # You may pin to the exact commit or the version.
        uses: docker/build-push-action@v2.7.0
        with:
          builder: ${{ steps.buildx.outputs.name }}
          # Build's context is the set of files located in the specified PATH or URL
          context: ${{ env.module_path }}
          # Path to the Dockerfile
          file: "${{ env.module_path }}/Dockerfile.${{ matrix.arch.name }}"
          # Push is a shorthand for --output=type=registry
          push: true
          # List of SSH agent socket or keys to expose to the build
          ssh: # optional
          # List of tags
          tags: ${{ env.registry_name }}/${{ env.image_name }}:${{ steps.docker-tag.outputs.tag }}-${{ matrix.arch.name }}
          platforms: ${{ matrix.arch.platformName }}
          
  publish: 
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: docker-tag
        uses: yuya-takeyama/docker-tag-from-github-ref-action@v1

      - name: Docker Login
        # You may pin to the exact commit or the version.
        uses: docker/login-action@v2.0.0
        with:
          registry: ${{ env.registry_name }}
          username:  ${{ github.actor }}
          password:  ${{ secrets.GITHUB_TOKEN }}

      - name: Create the manifest
        run: docker manifest create ${{ env.registry_name }}/${{ env.image_name }}:${{ steps.docker-tag.outputs.tag }} --amend ${{ env.registry_name }}/${{ env.image_name }}:${{ steps.docker-tag.outputs.tag }}-amd64 --amend ${{ env.registry_name }}/${{ env.image_name }}:${{ steps.docker-tag.outputs.tag }}-arm64v8

      - name: Publish  the manifest
        run: docker manifest push ${{ env.registry_name }}/${{ env.image_name }}:${{ steps.docker-tag.outputs.tag }}

      - name: Create the manifest
        run: docker manifest create ${{ env.registry_name }}/${{ env.image_name }}:latest --amend ${{ env.registry_name }}/${{ env.image_name }}:${{ steps.docker-tag.outputs.tag }}-amd64 --amend ${{ env.registry_name }}/${{ env.image_name }}:${{ steps.docker-tag.outputs.tag }}-arm64v8

      - name: Publish  the manifest
        run: docker manifest push ${{ env.registry_name }}/${{ env.image_name }}:latest
